name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "557764f3-83e6-4ad0-b427-cd42bf725b07" \
            --password "nMc8Q~-BGQo4fN5-jHC-CZ9wEcsMAwAqA-_erc~k" \
            --tenant "5567a211-c5c0-42ff-990b-03aa0d9c9a50"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "bc9d2c5e-f99f-4142-8f22-8f6dae37180d"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            
            --username "9c207db5-cd16-426e-b1d5-17461f7c4858" \
            --password "WnMc8Q~-BGQo4fN5-jHC-CZ9wEcsMAwAqA-_erc~k" \
            --tenant "5567a211-c5c0-42ff-990b-03aa0d9c9a50"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "bc9d2c5e-f99f-4142-8f22-8f6dae37180d"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
